# Generated by Django 5.0.3 on 2024-03-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_name',
        ),
    ]
